from turtle import*
from math import*

speed(0)
delay(0)

LENGTH = 10 #490 / 49 = 10

def part1():
    pencolor("darkred")
    fillcolor("darkred")
    penup()
    fd(2 * LENGTH)
    pendown()
    begin_fill()
    fd(7 * LENGTH)
    lt(90)
    fd(9 * LENGTH)
    lt(90)
    fd(9 * LENGTH)
    lt(90)
    fd(7 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(6 * LENGTH)
    rt(90)
    fd(7 * LENGTH)
    rt(90)
    fd(7 * LENGTH)
    rt(90)
    fd(6 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(180)
    end_fill()
    penup()
    fd(2 * LENGTH)
    rt(90)
    pendown()
    begin_fill()
    for i in range(0, 4):
        fd(5 * LENGTH)
        lt(90)
    end_fill()
    penup()
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    pendown()
    fillcolor("white")
    begin_fill()
    for i in range(0, 4):
        fd(3 * LENGTH)
        lt(90)
    end_fill()
    penup()
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    pendown()
    fillcolor("darkred")
    begin_fill()
    for i in range(0, 4):
        fd(LENGTH)
        lt(90)
    end_fill()
    penup()
    rt(90)
    fd(4 * LENGTH)
    rt(90)
    fd(4 * LENGTH)
    lt(180)
    pendown()
    begin_fill()
    for i in range(0, 4):
        fd(LENGTH)
        lt(90)
    end_fill()

def part2():
    pencolor("darkred")
    fillcolor("darkred")
    begin_fill()
    fd(6 * LENGTH)
    lt(90)
    fd(5 * LENGTH)
    lt(90)
    fd(2 * LENGTH)
    rt(90)
    fd(LENGTH)
    rt(90)
    fd(3 * LENGTH)
    rt(90)
    fd(6 * LENGTH)
    lt(90)
    fd(4 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(3 * LENGTH)
    rt(90)
    fd(6 * LENGTH)
    lt(90)
    fd(5 * LENGTH)
    lt(90)
    fd(2 * LENGTH)
    rt(90)
    fd(LENGTH)
    rt(90)
    fd(3 * LENGTH)
    rt(90)
    fd(7 * LENGTH)
    rt(90)
    fd(6 * LENGTH)
    lt(90)
    fd(2 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(6 * LENGTH)
    lt(90)
    fd(9 * LENGTH)
    lt(90)
    fd(5 * LENGTH)
    lt(90)
    fd(2 * LENGTH)
    rt(90)
    fd(LENGTH)
    rt(90)
    fd(3 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(4 * LENGTH)
    lt(90)
    fd(2 * LENGTH)
    rt(90)
    fd(LENGTH)
    rt(90)
    fd(3 * LENGTH)
    rt(90)
    fd(5 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    end_fill()

def rama():
    penup()
    bk(15 * LENGTH)
    lt(90)
    fd(15 * LENGTH)
    rt(90)
    pendown()
    for i in range(0, 4):
        for y in range(0, 3):
            part2()
            penup()
            fd(10 * LENGTH)
            pendown()
        fd(LENGTH)
        part1()
        rt(90)
    penup()
    fd(15 * LENGTH)
    rt(90)
    fd(15 * LENGTH)
    lt(90)
    pendown()

rama()
