from turtle import*
from math import*

speed(0)
delay(0)

LENGTH = 8

def part1():
    fillcolor("green")
    penup()
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    pendown()
    begin_fill()
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    rt(90)
    fd(2 * LENGTH)
    rt(90)
    fd(2 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(4 * LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(2 * LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    end_fill()
    penup()
    bk(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    pendown()

def part2():
    fillcolor("yellow")
    penup()
    fd(LENGTH)
    pendown()
    begin_fill()
    fd(4 * LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(2 * LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    rt(90)
    fd(2 * LENGTH)
    rt(90)
    fd(2 * LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    lt(90)
    fd(LENGTH)
    rt(90)
    fd(LENGTH)
    lt(90)
    end_fill()
    penup()
    bk(LENGTH)
    pendown()

def main(n):
    switch = True
    
    for i in range(0, n):
        for y in range(0, n - i):
            if switch:
                part1()
            else:
                part2()
            penup()
            fd(5.5 * LENGTH)
            lt(90)
            fd(2.5 * LENGTH)
            rt(90)
            pendown()
        penup()
        bk((n - i) * 5.5 * LENGTH)
        rt(90)
        fd((n - i) * 2.5 * LENGTH)
        lt(180)
        fd(4 * LENGTH)
        rt(90)
        pendown()
        if switch:
            switch = False
        else:
            switch = True

main(14)
